dist: xenial
language: java
jdk:
  - openjdk8
before_install:
  - sudo apt-get install -y python-pip
  - sudo pip install ansible==2.8.1
  - ansible --version
install:
  - mvn clean package
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  skip_cleanup: true
  on:
    tags: true
